# MongoDB Atlas Connection
spring.data.mongodb.uri=mongodb+srv://user:mongoindeed@indeed-application.2cnjzm4.mongodb.net/Indeed-Application?retryWrites=true&w=majority
spring.data.mongodb.database=Indeed-Application
spring.data.mongodb.auto-index-creation=true

# Server Configuration
server.port=${PORT:10000}
server.servlet.context-path=/
server.error.whitelabel.enabled=false

# Logging
logging.level.root=INFO
logging.level.com.indeed.server=DEBUG

# Application Name
spring.application.name=indeed-server

