# MongoDB Atlas Connection
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}
spring.data.mongodb.database=${SPRING_DATA_MONGODB_DATABASE:indeeddb}
spring.data.mongodb.auto-index-creation=${SPRING_DATA_MONGODB_AUTO_INDEX_CREATION:true}

# Server Configuration
server.port=${PORT:8080}
server.error.whitelabel.enabled=false

# Spring configuration
spring.config.additional-location=classpath:/application.properties

